[[ch01_intro_what_is_Nano]]

== Introduction

=== What Is Nano?

Nano is a collection of concepts and technologies that form the basis of a digital money ecosystem.  Units of currency called Nano are used to store and transmit value among participants in the Nano network.  Nano users communicate with each other using the Nano protocol primarily via the internet, although other transport networks can also be used(?). The Nano protocol stack, available as open source software, can be run on a wide range of computing devices, including laptops and smartphones, making the technology easily accessible.

Users can transfer Nano over the network to do just about anything that can be done with conventional currencies, including buy and sell goods, send money to people or organizations, or extend credit. Nano can be purchased, sold, and exchanged for other currencies at specialized currency exchanges. Nano in a sense is the perfect form of money for the internet because it is truly fast, secure, borderless and completly feeless.

Unlike traditional currencies, Nano are entirely virtual. There are no physical coins or even digital coins per se. The coins are implied in transactions that transfer value from sender to recipient. Users of Nano own keys that allow them to prove ownership of Nano in the Nano network. With these keys they can sign transactions to unlock the value and spend it by transferring it to a new owner. Keys are often stored in a digital wallet on each user’s computer, smartphone or online. Possession of the key that can sign a transaction is the only prerequisite to spending Nano, putting the control entirely in the hands of each user.

Nano is a distributed, peer-to-peer system. As such there is no "central" server or point of control. Nano uses a block-lattice architecture, meaning that each account has its own blockchain, creating near instanteneous transactions and in theory unlimited scalability. The separate blockchains update ascynchronously  to the rest of the network, drasticly lowering the overhead.
In Nano transactions keep track of account balances rather than transaction amounts, allowing aggressive database pruning without compromising security.

Behind the scenes, Nano is also the name of the protocol, a peer-to-peer network, and a distributed computing innovation. The Nano currency is really only the first application of this invention. Nano represents the culmination of decades of research in cryptography, distributed systems and crypto currencies and includes four key innovations brought together in a unique and powerful combination. Nano consists of:

* A decentralized peer-to-peer network (the Nano protocol)
* A public transaction ledger (the blockchain)
* The Block-Lettuce architecture
* A mechanism for reaching global decentralized consensus on the valid blockchain (Delegated Proof-of-Stake)

As a developer, I see Nano as akin to the internet of money2.0, a network for propagating value and securing the ownership of digital assets via distributed computation. There's a lot more to Nano than first meets the eye.

In this chapter we'll get started by explaining some of the main concepts and terms, getting the necessary software, and using Nano for simple transactions. In following chapters we'll start unwrapping the layers of technology that make Nano possible and examine the inner workings of the Nano network and protocol.

Digital Currencies Before Nano
The emergence of viable digital money is closely linked to developments in cryptography. This is not surprising when one considers the fundamental challenges involved with using bits to represent value that can be exchanged for goods and services. Three basic questions for anyone accepting digital money are:

Can I trust that the money is authentic and not counterfeit?

Can I trust that the digital money can only be spent once (known as the “double-spend” problem)?

Can I be sure that no one else can claim this money belongs to them and not me?

Issuers of paper money are constantly battling the counterfeiting problem by using increasingly sophisticated papers and printing technology. Physical money addresses the double-spend issue easily because the same paper note cannot be in two places at once. Of course, conventional money is also often stored and transmitted digitally. In these cases, the counterfeiting and double-spend issues are handled by clearing all electronic transactions through central authorities that have a global view of the currency in circulation. For digital money, which cannot take advantage of esoteric inks or holographic strips, cryptography provides the basis for trusting the legitimacy of a user’s claim to value. Specifically, cryptographic digital signatures enable a user to sign a digital asset or transaction proving the ownership of that asset. With the appropriate architecture, digital signatures also can be used to address the double-spend issue.

When cryptography started becoming more broadly available and understood in the late 1980s, many researchers began trying to use cryptography to build digital currencies. These early digital currency projects issued digital money, usually backed by a national currency or precious metal such as gold.

Although these earlier digital currencies worked, they were centralized and, as a result, were easy to attack by governments and hackers. Early digital currencies used a central clearinghouse to settle all transactions at regular intervals, just like a traditional banking system. Unfortunately, in most cases these nascent digital currencies were targeted by worried governments and eventually litigated out of existence. Some failed in spectacular crashes when the parent company liquidated abruptly. To be robust against intervention by antagonists, whether legitimate governments or criminal elements, a decentralized digital currency was needed to avoid a single point of attack. Bitcoin is such a system, decentralized by design, and free of any central authority or point of control that can be attacked or corrupted.


